const productData = [
    {
       id : 1,
       name : '',
       price : '',
       brand : '',
       category : 'jackets',
       description : '', 
       image : '',
    },
    {
        id : 2,
        name : '',
        price : '',
        brand : '',
        category : 'jackets',
        description : '', 
        image : '',
     },
     {
        id : 3,
        name : '',
        price : '',
        brand : '',
        category : 'jackets',
        description : '', 
        image : '',
     },
     {
        id : 4,
        name : '',
        price : '',
        brand : '',
        category : 'jackets',
        description : '', 
        image : '',
     },
     {
        id : 5,
        name : '',
        price : '',
        brand : '',
        category : 'jackets',
        description : '', 
        image : '',
     },
     {
        id : 6,
        name : '',
        price : '',
        brand : '',
        category : 'clothes',
        description : '',
        image : '',
 
     },
     {
        id : 7,
        name : '',
        price : '',
        brand : '',
        category : 'clothes',
        description : '', 
        image : '',
     },
     {
        id : 8,
        name : '',
        price : '',
        brand : '',
        category : 'clothes',
        description : '', 
        image : '',
    },
     {
        id : 9,
        name : '',
        price : '',
        brand : '',
        category : 'clothes',
        description : '', 
        image : '',
     },
     {
        id : 10,
        name : '',
        price : '',
        brand : '',
        category : 'clothes',
        description : '', 
        image : '',
     },
     {
        id : 11,
        name : '',
        price : '',
        brand : '',
        category : 'jeans',
        description : '', 
        image : '',
     },
     {
        id : 12,
        name : '',
        price : '',
        brand : '',
        category : 'jeans',
        description : '', 
        image : '',
     },
     {
        id : 13,
        name : '',
        price : '',
        brand : '',
        category : 'jeans',
        description : '', 
        image : '',
     },
     {
        id : 14,
        name : '',
        price : '',
        brand : '',
        category : 'jeans',
        description : '', 
        image : '',
     },
]
module.exports = productData;